### ISSUE TITLE
[Question] code for runnig evaluations and generate radar chart

### ISSUE THREAD

**Issue by leehanchung** [adlnlp/FinLLMs#1]
Hi,

Where can I find the code for running the evaluations? Or to generate radar charts?

Or the evaluation tables are copied from the papers mentioned in the paper?

**Comment by JeanLee-AI** [comment]
Hi @leehanchung,

Thank you very much for your interest in our research!

The evaluation results are referenced from original or analysis research, and SOTA results from task-specific models. You can find more details in our [FinLLMs paper](https://arxiv.org/pdf/2402.02315). We have attached an image from our revised paper, which will be published soon in a journal.

![Screenshot 2024-10-09 at 16 34 21](https://github.com/user-attachments/assets/de8f88c0-a5de-4d72-acca-471a901000c3)
 
If you'd like to run the model for evaluation, we recommend either the GitHub repository shared in the [IJCAI2024-challenge](https://github.com/The-FinAI/PIXIU/blob/main/README.ijcai_challenge.md) or the recently launched [open FinLLM leaderboard](https://huggingface.co/spaces/TheFinAI/Open-Financial-LLM-Leaderboard). 

Thank you!
